### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by tr37ion** [data-modul/slim#1]
Is this project still in development or can we consider it as abandoned? Its not a problem, just to know how to treat it within distros. Afaik: systemd support is missing?!

**Comment by silvio** [comment]
Hey @tr37ion, 

This repo is only a reup to build of our old releases, because the original repo was not found anymore on the old project site.

[Lightdm] seems a good replacement for slim.

[Lightdm]: http://www.freedesktop.org/wiki/Software/LightDM/
